# Generated by Django 2.0.6 on 2018-06-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20180605_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'ordering': ['nome_restaurante']},
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='valor',
        ),
    ]
