# Generated by Django 2.0.6 on 2018-06-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20180608_1435'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome_produto']},
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='restaurantes.Restaurante', verbose_name='Lista de Restaurantes Cadastrados'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
