# Generated by Django 2.0.5 on 2018-06-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantes', '0002_auto_20180605_1752'),
        ('produtos', '0001_initial'),
        ('clientes', '0003_auto_20180605_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pessoas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Pessoa', verbose_name='Lista de clientes cadastrados')),
                ('produtos', models.ManyToManyField(to='produtos.Produto', verbose_name='Lista de Produtos')),
                ('restaurantes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurantes.Restaurante', verbose_name='Lista de restautantes cadastrados')),
            ],
        ),
    ]
