# Generated by Django 2.0.5 on 2018-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['numero'], 'verbose_name_plural': 'pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
