# Generated by Django 2.0.5 on 2018-06-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedidos', '0002_auto_20180605_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='produtos.Produto', verbose_name='Lista de Produtos'),
        ),
    ]
