# Generated by Django 2.0.5 on 2018-06-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20180605_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
    ]
