# Generated by Django 2.0.6 on 2018-06-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='restaurantes',
        ),
    ]
