# Generated by Django 2.0.6 on 2018-06-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20180608_1442'),
        ('pedidos', '0006_remove_pedido_restaurantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='produtos.Produto', verbose_name='Lista de Produtos'),
        ),
    ]
