# Generated by Django 2.0.6 on 2018-06-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20180611_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['pk'], 'verbose_name_plural': 'pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
