# Generated by Django 2.0.5 on 2018-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoas',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
