# Generated by Django 2.0.5 on 2018-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=100)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('idade', models.IntegerField(max_length=3)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
