# Generated by Django 2.0.6 on 2018-06-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180605_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome_pessoa']},
        ),
    ]
